services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: projectdevops-app
    expose:
      - "5000"
    depends_on:
      - db
    networks:
      - front_net
      - back_net

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops
      POSTGRES_DB: devops_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - back_net

  migration_runner:
    image: projectdevops-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: devops_db
      DB_USER: devops
      DB_PASSWORD: devops
    command: ["python", "migrations/run_migrations.py"]
    restart: "no"
    networks:
      - back_net

  nginx:
    image: nginx:1.25
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    restart: always
    networks:
      - front_net

  seed_runner:
    image: projectdevops-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: devops_db
      DB_USER: devops
      DB_PASSWORD: devops
    volumes:
      - seed_output:/seed_output
    command: ["python", "seed/run_seed.py"]
    restart: "no"
    networks:
      - back_net

networks:
  front_net:
  back_net:

volumes:
  db_data:
  nginx_logs:
  seed_output:

